version: '3.8'

services:
  backup-service:
    build: .
    container_name: database-backup-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./backups:/app/backups
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backup-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backup-network:
    driver: bridge