version: '3.8'

services:
  backup-service:
    build: 
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: database-backup-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ${BACKUP_DIR}:/app/backups
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backup-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backup-network:
    driver: bridge